// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package version

import (
	"backend/api/version"
	v1 "backend/api/version/v1"
	"backend/internal/config"
)

type option struct {
	ac config.AboutSoftware
}

func defaultOption() option {
	return option{
		ac: config.AboutSoftware{
			Version:    "0.0.1",
			Leader:     "Unknown",
			Developers: []string{"Alice", "Bob", "Charlie", "Davis"},
		},
	}
}
func WithAboutConfig(cfg config.AboutSoftware) ControllerV1OptionFunc {
	return func(opt *option) {
		opt.ac = cfg
	}
}

type ControllerV1 struct {
	option

	cacheAbout *v1.AboutRes
}

func (c *ControllerV1) build() {
	c.cacheAbout = &v1.AboutRes{
		Version:    c.option.ac.Version,
		Leader:     c.option.ac.Leader,
		Developers: c.ac.Developers,
	}
}

type ControllerV1OptionFunc func(opt *option)

func NewV1(options ...ControllerV1OptionFunc) version.IVersionV1 {
	ctrl := &ControllerV1{
		option: defaultOption(),
	}

	for _, o := range options {
		o(&ctrl.option)
	}
	ctrl.build()

	return ctrl
}
