// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share

import (
	"backend/api/share"
	v1 "backend/api/share/v1"
	"backend/internal/config"
	"backend/internal/logic"

	"github.com/gogf/gf/v2/net/ghttp"
)

type option struct {
	argonConfig  *config.ArgonConfig
	cryptoConfig *config.Item
}

type ControllerV1 struct {
	options *option

	hu *logic.HashUtils
	cu *logic.CryptoUtils
}

type OptionFunc func(c *ControllerV1)

func NewV1(options ...OptionFunc) share.IShareV1 {
	ctrl := &ControllerV1{
		options: &option{},
		hu:      logic.NewHashUtils(),
		cu:      logic.NewCryptoUtils(),
	}

	ctrl.injectDefaultConfig()

	for _, option := range options {
		option(ctrl)
	}
	ctrl.build()
	return ctrl
}

func (c *ControllerV1) injectDefaultConfig() {
	c.options.argonConfig = &config.ArgonConfig{
		Secret:      "DO-NOT-USE-THIS-SECRET-IN-PRODUCTION",
		Memory:      64 * 1024, // 64MB
		Iterations:  3,
		Parallelism: 2,
		SaltLength:  16,
		KeyLength:   32,
	}
	c.options.cryptoConfig = &config.Item{
		ItemSeal: config.ItemSeal{
			ShareKey: "DO-NOT-USE-THIS-KEY-IN-PRODUCTION",
			KeySize:  32,
			Nonce:    "ABCDABCDABCD", // 12字节
		},
		ItemStorage: config.ItemStorage{},
	}
}

func WithArgonConfig(cfg *config.ArgonConfig) OptionFunc {
	return func(c *ControllerV1) {
		c.options.argonConfig = cfg
	}
}
func WithCryptoConfig(cfg *config.Item) OptionFunc {
	return func(c *ControllerV1) {
		c.options.cryptoConfig = cfg
	}
}

func (c *ControllerV1) build() {
	c.hu.BuildWithConfig(c.options.argonConfig)
	c.cu.BuildWithConfig(c.options.cryptoConfig)
}

type Msg struct { // 用于SSE期间做回复
	Progress int                 `json:"progress"` // 进度
	Message  string              `json:"message"`
	Data     *v1.ShareRefreshRes `json:"data"`
}

func (c *ControllerV1) beginSSE(r *ghttp.Response) {
	r.Header().Set("Content-Type", "text/event-stream")
	r.Header().Set("Cache-Control", "no-cache")
	r.Header().Set("Connection", "keep-alive")

	r.Flush()
}
func (c *ControllerV1) sendMsgAndFlush(r *ghttp.Response, msg string) {
	c.sendAndFlush(r, Msg{Message: msg})
}
func (c *ControllerV1) sendAndFlush(r *ghttp.Response, msg Msg) {
	r.WriteJson(msg)
	r.Write("\n\n") // 换两次行, 便于前端搞清楚什么时候是一段话什么时候不是
	r.Flush()
}
