// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package item

import (
	"backend/api/item"
	"backend/internal/config"
	"backend/internal/logic"
	crypv2 "backend/internal/logic/crypto/v2"
)

type option struct {
	config.Item
	config.ArgonConfig
}

type ControllerV1 struct {
	options *option

	fu  *logic.FileUtils
	cu  *logic.CryptoUtils
	icu logic.ICryptoUtils
	hu  *logic.HashUtils
}
type OptionFunc func(*option)

func (c *ControllerV1) injectDefaultConfig() {
	c.options.Item = config.DefaultItemConfig()
	c.options.ArgonConfig = config.DefaultArgonConfig()
}
func (c *ControllerV1) build() {
	c.fu.BuildWithConfig(&c.options.Item)
	c.cu.BuildWithConfig(&c.options.Item)
	c.icu.BuildWithConfig(c.options.Item)
	c.hu.BuildWithConfig(&c.options.ArgonConfig)
}

func NewV1(options ...OptionFunc) item.IItemV1 {
	ctrl := &ControllerV1{
		fu:  logic.NewFileUtils(),
		icu: crypv2.NewICryptoUtils(),
		cu:  logic.NewCryptoUtils(),
		hu:  logic.NewHashUtils(),
	}

	ctrl.options = &option{}
	for _, optionFunc := range options {
		optionFunc(ctrl.options)
	}
	ctrl.build()
	return ctrl
}

func WithArgonConfig(argon *config.ArgonConfig) OptionFunc {
	return func(o *option) {
		if argon != nil {
			o.ArgonConfig = *argon
		}
	}
}
func WithCryptoConfig(item *config.Item) OptionFunc {
	return func(o *option) {
		if item != nil {
			o.Item = *item
		}
	}
}
