// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"backend/api/user"
	"backend/internal/config"

	"github.com/pilinux/argon2"
)

type Option struct {
	ArgonSecret  string
	Argon2Params argon2.Params
}
type Utilities struct {
	hashGen    func(password string) (string, error)
	hashVerify func(password string, hash string) (bool, error)
}

// build
//
// 接受Option参数, 用于构建套具; 不使用大写字母开头的原因是会与Controller的Build路由构建方法冲突
func (u *Utilities) build(opt Option) {
	u.hashGen = func(password string) (string, error) {
		return argon2.CreateHash(password, opt.ArgonSecret, &opt.Argon2Params)
	}
	u.hashVerify = func(password string, hash string) (bool, error) {
		return argon2.ComparePasswordAndHash(password, hash, opt.ArgonSecret)
	}
}

type OptionFunc func(*Option)

func withDefaultArgon2Params() OptionFunc {
	return func(o *Option) {
		o.ArgonSecret = "YOUR_EXTRA_SECRET"
		o.Argon2Params = *argon2.DefaultParams
	}
}
func WithArgon2Config(cfg config.ArgonConfig) OptionFunc {
	return func(o *Option) {
		o.ArgonSecret = cfg.Secret
		o.Argon2Params = argon2.Params{
			Iterations:  cfg.Iterations,
			KeyLength:   cfg.KeyLength,
			Memory:      cfg.Memory,
			Parallelism: cfg.Parallelism,
			SaltLength:  cfg.SaltLength,
		}
	}
}

type ControllerV1 struct {
	option Option
	*Utilities
}

func NewV1(options ...OptionFunc) user.IUserV1 {
	ctrl := &ControllerV1{
		Utilities: &Utilities{},
	}

	withDefaultArgon2Params()(&ctrl.option)
	for _, option := range options {
		option(&ctrl.option)
	}

	ctrl.build(ctrl.option)
	return ctrl
}

type ControllerV2 struct {
	option Option
	*Utilities
}

func NewV2(options ...OptionFunc) user.IUserV2 {
	ctrl := &ControllerV2{
		Utilities: &Utilities{},
	}

	withDefaultArgon2Params()(&ctrl.option)
	for _, option := range options {
		option(&ctrl.option)
	}

	ctrl.build(ctrl.option)
	return ctrl
}

type ControllerV3 struct{}

func NewV3() user.IUserV3 {
	return &ControllerV3{}
}
