// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package calc

import (
	"backend/api/calc"
)

type ControllerV1 struct{}

func NewV1() calc.ICalcV1 {
	return &ControllerV1{}
}
