// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
	"backend/internal/model/entity"
	"context"

	"github.com/gogf/gf/v2/errors/gerror"
)

// employeesDao is the data access object for the table employees.
// You can define custom methods on it to extend its functionality as needed.
type employeesDao struct {
	*internal.EmployeesDao
}

var (
	// Employees is a globally accessible object for table employees operations.
	Employees = employeesDao{internal.NewEmployeesDao()}
)

// Add your custom methods and functionality below.

// GetLowestJob
//
// 获取最低一级的岗位信息, 用于创建员工信息
//
// 注意:
//
// 【2026年4月25日】当数据库中有不止一个最低级的岗位时, 现有逻辑无法确保会获取到哪一个岗位
func GetLowestJob(ctx context.Context) (res *entity.Jobs, err error) {
	res = &entity.Jobs{}
	err = Jobs.Ctx(ctx).
		Where("role_privilege=1").
		Limit(1).
		Scan(res)

	if res.Job == "" {
		return nil, gerror.New("无法获取到最低一级的岗位")
	}

	return
}
