// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// itemMembersDao is the data access object for the table item_members.
// You can define custom methods on it to extend its functionality as needed.
type itemMembersDao struct {
	*internal.ItemMembersDao
}

var (
	// ItemMembers is a globally accessible object for table item_members operations.
	ItemMembers = itemMembersDao{internal.NewItemMembersDao()}
)

// Add your custom methods and functionality below.

type ItemOpsRole = string

const (
	ItemOwner  ItemOpsRole = "owner"  // 可读可写
	ItemMember             = "member" // 只能看不能改
)

type ItemSubmitStatus = int // 申请审批状态
const (
	SubmissionRemoved  ItemSubmitStatus = iota // 已移除
	SubmissionApproved                         // 审批通过
	SubmissionPending                          // 待审批
)
