// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// itemsDao is the data access object for the table items.
// You can define custom methods on it to extend its functionality as needed.
type itemsDao struct {
	*internal.ItemsDao
}

var (
	// Items is a globally accessible object for table items operations.
	Items = itemsDao{internal.NewItemsDao()}
)

// Add your custom methods and functionality below.
