// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// sharesDao is the data access object for the table shares.
// You can define custom methods on it to extend its functionality as needed.
type sharesDao struct {
	*internal.SharesDao
}

var (
	// Shares is a globally accessible object for table shares operations.
	Shares = sharesDao{internal.NewSharesDao()}
)

// Add your custom methods and functionality below.

type ShareType = string

const (
	ShareTypeAuth     ShareType = "auth"
	ShareTypeRecovery ShareType = "recovery"
	ShareTypeDevice   ShareType = "device"
)

type ShareStatus = string

const (
	ShareStatusActive  ShareStatus = "active"
	ShareStatusExpired ShareStatus = "expired"
	ShareStatusRevoked ShareStatus = "revoked"
)
